import Head from 'next/head'
import styles from '../styles/Home.module.css'
import AnimateText from './animation-wrapper';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Animations are  <AnimateText dictionary={['exciting', 'exhausting']}>funny</AnimateText>. Try them out</p>
    </div>
  )
}
